var htmlBody = $('html, body')
    body = $('body'),
    title = $('title'),
    header = '<header></header>',
    nav = '<nav></nav>',
    ul = '<ul></ul>',
    li = '<li></li>',
    a = '<a></a>'
    i = '<i></i>',
    div = '<div></div>',
    h1 = '<h1></h1>',
    span = '<span></span>',
    p = '<p></p>',
    section = '<section></section>',
    img = '<img>',
    input = '<input>',
    label = '<label></label>',
    ionIcon = '<ion-icon></ion-icon>',
    button = $('<button></button>'),
    logo = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Xr9_8mqDwGPkQJEioXha69cGjwiwTOSryQ&usqp=CAU'

body.append($(header)
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('checked', '').attr('id', 'hom'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'con'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'sch'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'opt'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'abo'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'calc'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'cal'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'mus'))
  .append($(input).attr('type', 'radio').attr('name', 'slider').attr('id', 'sig'))
  .append($(nav).append($(ul)
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(label).attr('for', 'hom').addClass('home show-home')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'home-outline'))
        )
        .append($(span).addClass('text').text('Home'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'con').addClass('content show-content')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'grid-outline'))
        )
        .append($(span).addClass('text').text('Content'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'sch').addClass('scholl show-scholl')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'library-outline'))
        )
        .append($(span).addClass('text').text('Scholl'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'opt').addClass('settings show-options')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'options-outline'))
        )
        .append($(span).addClass('text').text('Options'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'abo').addClass('about show-help')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'help-outline'))
        )
        .append($(span).addClass('text').text('Help'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'calc').addClass('calculator show-calculator')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'calculator-outline'))
        )
        .append($(span).addClass('text').text('Calculator'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'cal').addClass('calendar show-calendar')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'calendar-outline'))
        )
        .append($(span).addClass('text').text('Calendar'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'mus').addClass('play-music show-play_music')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'musical-notes-outline'))
        )
        .append($(span).addClass('text').text('Play Music'))
      )
    )
    .append($(li)
      .append($(span).addClass('border'))
      .append($(span).addClass('border'))
      .append($(span).addClass('path'))
      .append($(label).attr('for', 'sig').addClass('sign-out show-sign_out')
        .append($(span).addClass('icon')
          .append($(ionIcon).attr('name', 'log-out-outline'))
        )
        .append($(span).addClass('text').text('Sign Out'))
      )
    )
    .append($(div).addClass('slider')
      .append($(span).addClass('path'))
    )
  ))
  .append($(div).addClass('menu-btn')
    .append($(button).attr('id', 'toggle-menu')
      .append($(span).addClass('bar'))
    )
  )
)

body.append($(div).addClass('main')
  .append($(section).attr('id', 'home')
    .append($(div).addClass('home-content')
      .append($(h1).addClass('title-content').text('Home'))
    )
  )
  .append($(section).attr('id', 'content')
    .append($(div).addClass('content-content')
      .append($(h1).addClass('title-content').text('Content'))
      .append($(div).addClass('boxes')
        .append($(div).addClass('box').attr('style', '--i:1;')
          .append($(div).addClass('image')
            .append($(img).attr('src', '../images/mp.jpg'))
          )
          .append($(div).addClass('box-content')
            .append($(div).addClass('title')
              .append($(h1).text('Mapeamento Estruturado'))
            )
            .append($(div).addClass('info')
              .append($(span).text('Professor: ')
                .append($(p).text('Antônio Pinto'))
              )
              .append($(span).text('Conteúdo: ')
                .append($(p).text('Atividades'))  
              )
            )
            .append($(div).addClass('btn')
              .append($(button).text('View More'))
            )
          )
        )
        .append($(div).addClass('box').attr('style', '--i:2;')
          .append($(div).addClass('image')
            .append($(img).attr('src', '../images/tda-02.jpg'))
          )
          .append($(div).addClass('box-content')
            .append($(div).addClass('title')
              .append($(h1).text('Técnicas e Desenvolvimento de Augorítmos'))
            )
            .append($(div).addClass('info')
              .append($(span).text('Professor: ')
                .append($(p).text('Tartaruga'))
              )
              .append($(span).text('Conteúdo: ')
                .append($(p).text('Atividades'))  
              )
            )
            .append($(div).addClass('btn')
              .append($(button).text('View More'))
            )
          )
        )
        .append($(div).addClass('box').attr('style', '--i:3;')
          .append($(div).addClass('image')
            .append($(img).attr('src', '../images/oac.jpg'))
          )
          .append($(div).addClass('box-content')
            .append($(div).addClass('title')
              .append($(h1).text('Organização e Arquitetura de Conputadores'))
            )
            .append($(div).addClass('info')
              .append($(span).text('Professor: ')
                .append($(p).text('Garganta'))
              )
              .append($(span).text('Conteúdo: ')
                .append($(p).text('Atividades'))  
              )
            )
            .append($(div).addClass('btn')
              .append($(button).text('View More'))
            )
          )
        )
        .append($(div).addClass('box').attr('style', '--i:4;')
          .append($(div).addClass('image')
            .append($(img).attr('src', '../images/purple-galaxy-abstract-4k-oz-1920x1080.jpg'))
          )
          .append($(div).addClass('box-content')
            .append($(div).addClass('title')
              .append($(h1).text('Inglês'))
            )
            .append($(div).addClass('info')
              .append($(span).text('Professor: ')
                .append($(p).text('nulo'))
              )
              .append($(span).text('Conteúdo: ')
                .append($(p).text('Atividades'))  
              )
            )
            .append($(div).addClass('btn')
              .append($(button).text('View More'))
            )
          )
        )
      )
    )
  )
  .append($(section).attr('id', 'scholl')
    .append($(div).addClass('scholl-content')
      .append($(h1).addClass('title-content').text('Scholl'))
    )
  )
  .append($(section).attr('id', 'options')
    .append($(div).addClass('options-content')
      .append($(h1).addClass('title-content').text('Options'))
    )
  )
  .append($(section).attr('id', 'help')
    .append($(div).addClass('help-content')
      .append($(h1).addClass('title-content').text('Help'))
    )
  )
  .append($(section).attr('id', 'calculator')
    .append($(div).addClass('calculator-content')
      .append($(h1).addClass('title-content').text('Calculator'))
    )
  )
  .append($(section).attr('id', 'calendar')
    .append($(div).addClass('calendar-content')
      .append($(h1).addClass('title-content').text('Calendar'))
    )
  )
  .append($(section).attr('id', 'playMusic')
    .append($(div).addClass('playMusic-content')
      .append($(h1).addClass('title-content').text('Play Music'))
    )
  )
  .append($(section).attr('id', 'signOut')
    .append($(div).addClass('signOut-content')
      .append($(h1).addClass('title-content').text('Sign Out'))
    )
  )
  .append($(div).addClass('preloader-section')
    .append($(span).attr('style', '--i:1;'))
    .append($(span).attr('style', '--i:2;'))
    .append($(span).attr('style', '--i:3;'))
    .append($(span).attr('style', '--i:4;'))
    .append($(span).attr('style', '--i:5;'))
    .append($(span).attr('style', '--i:6;'))
    .append($(span).attr('style', '--i:7;'))
  )
  .append($(div).addClass('background')
    .append($(ul).addClass('circles')
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '1'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '2'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-3'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '4'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-8'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-2'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '2'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '7'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-1'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '5'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-4'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '1'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '-1'))
      )
      .append($(li).addClass('parallax')
        .append($(span).addClass('circle').attr('data-speed', '1'))
      )
    )
  )
)